### ISSUE TITLE
styles are broken for a newer version of Hangfire

### ISSUE THREAD

**Issue by FixRM** [bamotav/Hangfire.RecurringJobAdmin#100]
Hello @bamotav! Thank you for the tool. Unfortunately, one of latest HF updates broke some stiles of your page:

![image](https://github.com/bamotav/Hangfire.RecurringJobAdmin/assets/29232166/92847ab7-24dd-4e87-a23a-43041eabc5fb)

Can you please fix it?

**Comment by likan971** [comment]
Same here, the style is broken

**Comment by FixRM** [comment]
It looks like the issue is already fixed by contributors, but @bamotav didn't push update to NuGet. Meanwhile I stopped with this stupid fix:
```C#
app.Use(async (ctx, next) =>
{
    if (ctx.Request.Path.Value == "/hangfire/JobConfiguration/css/jobExtension")
    {
        using (var stream = typeof(WebStartup).Assembly.GetManifestResourceStream("Your.Namespace.cssfix.css"))
        using (var reader = new StreamReader(stream))
        {
            var content = reader.ReadToEnd();
            await ctx.Response.WriteAsync(content);
        }
    }
    else
    {
        await next();
    }
});
```
If somebody know less expensive option to override CSS, please let me know.

**Comment by AdCodicem** [comment]
Hi @bamotav 
Is there any plan to push this fix on Nuget ?
Thank you in advance :)

**Comment by leovannobeontag** [comment]
@bamotav This issue still seems to be relevant, is there any fix planned?

Edit: Words are cheap, I just created a PR
